project_templates:
  godot:
    folders: [scenes, scripts, assets]
    files:
      - project.godot
      - .gitattributes.txtfile
      - .gitignore.txtfile
      - README.md
  
  web:
    files:
      - index.html
      - script.js
      - style.css
      - README.md